### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by howardya** [kjartako/MS_VAR#2]
https://github.com/kjartako/MS_VAR/blob/71b0864c09b189a7c165b62d0db50912bdf0ad91/MS/Stan/MS_lkj.stan#L81

Should the line above be the following instead

```
fwd[i,j] = alphas[t-1,j] + logQ[j,i] + py[i];
```

Thank you.

**Comment by howardya** [comment]
Because logQ[x,y] is the log prob of state x transitioning to state y. 

and fwd[x,y] = log forward probability from state y to state x at time t

so fwd[x,y] = log probability of being in state y at time t-1 + log prob of transitioning from state y to state x + log prob of observing y at time t
= alphas[t-1,y] + logQ[y,x] + py[x]

Kindly let me know if my understanding is wrong.

**Comment by kjartako** [comment]
Thank you!
My original code was hardcoded for nreg=2, it appears I was too hasty when making the code more general.
Your suggestion is correct. To further improve interpretability, I will change the code (for all similar occurrences) to: 

`for(i in 1:nreg){
		  for (j in 1:nreg){
			fwd[i,j] = alphas[t-1,i] + logQ[i,j] + py[j];
		}
		  alphas[t,i]=log_sum_exp(fwd[,i]);
}`

So that fwd[i,j] = log forward probability from state i to state j at time t.
